export const data=[
    {
        id:1,
        name:"Kathakali",
        image:"kk.jpg",
        description:'Kathakali is a classical dance form of Kerala, demanding long years of training. Believed to have evolved from Ramanattam, another classical art form composed by Kottarakkara Thampuran, Kathakali incorporates the techniques of some of the major ritual art forms of Kerala.',
        desc2:"Famous around the world, Kathakali's magnificence has won great admiration for the state of Kerala. Proud that this renowned artfrom originated, was originated from Kerala’s shores over 300 years ago. It combines devotion, drama, dance, music, costumes and make up into a divine experience for all who get to view it. It retells the great stories of the past, mostly from Indian epics, and leaves one spellbound at the various intricacies involved in the performance. Every single quiver of the lips, flicker of the eyes or a movement involving the fingers twirling, has great significance.",
    },
    {
     id: 2,
        name:"Theyyam",
        image:"theyyam.jpg",
        description:"Theyyam is a famous ritual art form that originated in North Kerala which brings to life the great stories of our State. It encompasses dance, mime and music. It exalts the beliefs of the ancient tribals who gave a lot of importance to the worship of heroes and the spirits of their ancestors",
        desc2:"Theyyam is typically performed by people from castes and tribes like Pulayar, Vannan, Malayan, Anhoottan, Munnoottan, Mavilan, Koppalan, Velan, Chingathan, Kalanaadi, Paravan, Nalikeyavar etc. Of these Kalanaadi people perform only in Wayanad district, while Parava, Pampatha, Nalikeyavar perform in places north of Kerala like Udupi, Krishnapuram etc.",   
    },
    {
     id: 3,
    name:"Kathak",
    image:"kathak.jpg",
    description:"Kathak is one of the main genres of ancient Indian classical dance and is traditionally regarded to have originated from the travelling bards of North India referred as Kathakars or storytellers. These Kathakars wandered around and communicated legendary stories via music, dance and songs quite like the early Greek theatre. The genre developed during the Bhakti movement, the trend of theistic devotion which evolved in medieval Hinduism",
    desc2:"Kathak is one of the main genres of ancient Indian classical dance and is traditionally regarded to have originated from the travelling bards of North India referred as Kathakars or storytellers. These Kathakars wandered around and communicated legendary stories via music, dance and songs quite like the early Greek theatre. The genre developed during the Bhakti movement, the trend of theistic devotion which evolved in medieval Hinduism. The Kathakars communicate stories through rhythmic foot movements, hand gestures, facial expressions and eye work. This performing art that incorporates legends from ancient mythology and great Indian epics, especially from the life of Lord Krishna became quite popular in the courts of North Indian kingdoms. Three specific forms of this genre that is three gharanas (schools), which mostly differ in emphasis given to footwork versus acting, are more famous namely, the Jaipur gharana, the Benaras gharana and the Lucknow gharanaRussian scholar Natalia Lidova states that 'Natya Shastra' describes various theories of Indian classical dances including Tandava dance of Lord Shiva, methods of acting, standing postures, gestures, basic steps, bhava and rasa.Mary Snodgrass states that the tradition of this dance form is traced back to the 400 BCE. Bharhut, a village in the Satna district of Madhya Pradesh, India stands as a representative of early Indian art. The 2nd century BC panels found there illustrates sculptures of dancers in different vertical poses with arm positions that resemble Kathak steps, many of which reflect the 'pataka hasta' Mudra. The word Kathak is deduced from the Vedic Sanskrit term 'Katha' which means 'story' while the term kathaka that finds place in several Hindu epics and texts means the person who tells a story. Text-based analysis indicates Kathak as an ancient Indian classical dance form that presumably originated in Banaras or Varanasi and then spread its wings in Jaipur, Lucknow and many other regions of north and northwest India.",
},
    
    {
        id: 4,
        name:"kuchipudi",
        image:"kp.jpg",
        description:'Kuchipudi is one of the classical styles of Indian dance. Around the third and fourth decade of this century it emerged out of a long rich tradition of dance-drama of the same name.',
        desc2:"Kuchipudi, a pre-eminent Indian classical dance form counted among ten leading classical dance forms of India, is a dance-drama performance art that originated in a village of Krishna district of Andhra Pradesh, India. Similar to all leading Indian classical dance forms, Kuchipudi too evolved as a religious art rooting back to the age-old Hindu Sanskrit text 'Natya Shastra' and connects traditionally with temples, spiritual faiths and travelling bards. This ancient dance form finds place in the 10th century copper inscriptions and in 15th century texts like 'Machupalli Kaifat'. Traditionally it is regarded that the sanyassin of Advaita Vedanta sect, Tirtha Narayana Yati, and his disciple Siddhendra Yogi initiated, methodized and arranged the present day version of the dance form in 17th century. Usually performance repertoire of Kuchipudi that is broadly oriented on Lord Krishna and the tradition of Vaishnavism include an invocation, dharavu - short dance, nritta - pure dance and nritya - expressive dance respectively.The 10th century copper inscriptions validate the existence of Shaivism associated dance drama performance acts called 'Brahmana Melas' or 'Brahma Melas' in regions of South India with Telugu speaking populace.Brahmins performed this art during the medieval era. Vaishnavism that traditionally include Bhakti music and dance dedicated to Lord Krishna and evolved during the 2nd millennium presumably embraced this art form.  It developed in South India's Tamil region as 'Bhagavata Mela Nataka' and in Andhra region as Kuchipudi. Saskia Kersenboom mentions that both 'Bhagavata Mela Nataka' and Kuchipudi are closely related to the traditional theatre form of Karnataka called 'Yakshagana' and also incorporate Carnatic music like the latter, however the three retain their uniqueness palpable from their varied costume, format, innovative ideas and perceptions. Again author Manohar Laxman Varadpande states that this form came up in the late 13th century during the reign of the Eastern Ganga dynasty of Kalinga, who patronized art forms based on works of famed Sanskrit poet Jayadeva, most notably the 'Gita Govinda'. Such auspices of the monarch saw several dance-drama troupes and bards incorporating concepts based on Radha and Krishna in traditional Kuchipudi, which were locally called 'Vaishnava Bhagavatulus'.",
    },
        {
            id: 5,
            name:"Odissi",
            image:"od.jpg",
            description:'Odissi is traditionally a dance-drama genre of performance art, where the artist(s) and musicians play out a story, a spiritual message or devotional poem from the Hindu texts, using symbolic costumes, body movement, abhinaya (expressions) and mudras (gestures and sign language) set out in ancient Sanskrit literature. ',
            desc2:"Odissi or Orissi is one of the pre-eminent classical dance forms of India which originated in the Hindu temples of the eastern coastal state of Odisha in India. Its theoretical base trace back to 'Natya Shastra', the ancient Sanskrit Hindu text on the performing arts. Age-old tradition of Odissi is manifested from Odisha Hindu temples and various sites of archaeological significance that are associated with Hinduism, Jainism and Buddhism, the sculptures of which adorn dance postures of this art form. A form of illustrative anecdote of mythical and religious stories, devotional poems and spiritual ideas emoted by dancer with excellent body movements, expressions, impressive gestures and sign languages, its performance repertoire includes invocation, nrita, nritya, natya, and moksha. This dance form includes themes from Vaishnavism and others associated with Hindu gods and goddesses like Shiva, Surya and Shakti.Sites of archaeological and historical significance like caves and temples in Puri, Konarak and Bhubaneswar bear carvings that are historical manifestations of ancient art forms like music and dance. The heritage site of Udayagiri, the largest Buddhist complex in Odisha, houses the Manchapuri cave belongs to the reign of Kharavela, the Jaina king of Kalinga from the Mahameghavahana dynasty who ruled sometime around the 1st or 2nd century BCE. The cave depicts carvings of musicians and dance. Reference of music and dance are also found in Udayagiri's Hathigumpha Inscriptions that were inscribed by Kharavela. The antiquity of Odisha's musical tradition is also palpable from the account of discovery of a lithophone by the archaeologists that is made of polished basalt with 20 keys. It was unearthed in the archaeological site near Angul, Odisha called Sankarjang that dates back to around 1000 BCE.",
        },
            {
                id: 6,
                name:"Manipuri",
                image:"mani.jpg",
                description:'Manipuri is one of such India’s most prominent classical dance forms widely popular in its rich North East culture and traditions. Known for its elements of Hindu shastras such Vaishnavism, Radha-Krishna bhakti and Nataraja Natyam, Manipuri is known to be one of the greatest symbols of Bhakti Rasa.',
                desc2:"Manipuri dance is counted among major classical dance forms of India, especially noted for themes based on Vaishnavism and spectacular execution of 'Ras Lila', dance dramas based on love between Radha and Krishna. Other themes included in this art form associate with Shaktism, Shaivism and on the sylvan deities called Umang Lai during Manipuri festival 'Lai Haraoba'. This dance form is named after the north-eastern state of Manipur, India from where it originated but it has its roots in 'Natya Shastra', the age-old Sanskrit Hindu text. A mix of Indian and southeast Asian culture is palpable in this form. The age-old dance tradition of the place is manifested from great Indian epics, 'Ramayana' and 'Mahabharata', where the native dance experts of Manipur are referred as 'Gandharvas'. The Manipuris perform this religious art that aims at expressing spiritual values during Hindu festivals and other important cultural occasions like marriage.Traditionally the Manipuri people consider themselves to be the 'Gandharvas' mentioned in the Vedic texts who were singers, dancers and musicians associated with devas or the deities. Southeast Asian temples of early medieval period bear sculptures of 'Gandharvas' as dancers. The region is also mentioned as 'Gandharva-desa' in ancient Manipuri texts. Usha, the exalted dawn goddess in the 'Rig Veda' is traditionally accredited of creating female dance art and tutoring girls in the art. Conventionally this oral tradition of dance passed down verbally to women is famous in Manipur as 'Chingkheirol'. Manipur finds place in age-old Sanskrit texts including the great Indian epic, the 'Mahabharata', which mentions that one of the five Pandava brothers, Arjun met Chitrangada and fell in love with her in this beautiful valley. The ethnic majority of Meitei people call dance as 'Jagoi' and the traditional 'Lai Haraoba' festival observed in honour of the sylvan deities called Umang Lai includes several dance postures of Nataraja, an illustration of Lord Shiva as the cosmic ecstatic dancer, as also His disciple Tandu or Tangkhu. The 'Khamba Thoibi' dance is performed during 'Lai Haraoba'. It is a duet dance of male and female partners that is dedicated to the sylvan deity, Thangjing of Moiran, and associated with the Manipuri folklore of two lovers an orphan boy Khamba and a princess Thoibi, daughter of King Chinkhuba, from the epic 'Moirang Parba'.",               
           },
                {
                    id: 7,
                    name:"Mohiniyattam",
                    image:"mo.jpg",
                    description:"Mohiniyattam (Mohiniattam) is a classical dance form of Kerala in South India. The origin and popularity of this dance form is closely tagged to the great Tamil dance master Vadivelu, one of the Thanjavur quartets. One among the eight Indian classical dance forms, Mohiniyattam is a graceful dance to watch and is a solo recital by women.",
                    desc2:"Mohiniattam or Mohiniyattam is an Indian classical dance form that evolved in the state of Kerala, India, and is counted among the two popular dance arts of the state, the other being Kathakali. Although its roots date back to the age-old Sanskrit Hindu text on performing arts called 'Natya Shastra', similar to other Indian classical dance forms, Mohiniattam adheres to the Lasya type that showcases a more graceful, gentle and feminine form of dancing. Mohiniattam derives its name from the word 'Mohini', a female avatar of Lord Vishnu. Conventionally a solo dance performed by female artists, it emotes a play through dancing and singing where the song is customarily in Manipravala which is a mix of Sanskrit and Malayalam language and the recitation may be either performed by the dancer herself or by a vocalist with the music style being Carnatic.",
                },
                    {
                        id: 8,
                        name:"Sattriya",
                        image:"sat.jpg",
                        description:"Sattriya Dance has its origin in the 'Sattriyas' established by Mahapurush Srimanta Sankardev in the 15th and the 16th century. The Sattras were established for the propagation of Vaishnavism and later they became the religious, cultural and social hub for the people of Assam. The great Vaishnavite Saint has developed this dance form with its basic roots aligned with the characteristics of other forms of Indian classical dance",
                        desc2:"Sattriya Dance has its origin in the 'Sattriyas' established by Mahapurush Srimanta Sankardev in the 15th and the 16th century. The Sattras were established for the propagation of Vaishnavism and later they became the religious, cultural and social hub for the people of Assam. The great Vaishnavite Saint has developed this dance form with its basic roots aligned with the characteristics of other forms of Indian classical dance. Initially a part of the 'Ankia Naats', this dance form derived its name from the word 'Sattriyas' ..This dance form was originally performed in the Sattras and the Namghars by the male Bhokots as a part of religious rituals and for spreading the philosophy of Vaishnavism and was confined within the four walls of the sattras for several centuries.",
                    },
                        
    {
        id: 9,
        name:"Kalaripayattu",
        image:"kp.jpg",
        description:"Kalaripayattu is the martial art form of Kerala. Kalaripayattu's influence can be seen in most of the art forms of Kerala. In the past kalaris (combat arena or battle field) formed an integral part of the lives of the people. Without any gender discrimination boys and girls in their childhood would be sent to the Kalaris for practicing. With social life undergoing changes, the position of Kalaris and their influence changed",
        desc2:"Kalaripayattu is the martial art form of Kerala. Kalaripayattu's influence can be seen in most of the art forms of Kerala. In the past kalaris (combat arena or battle field) formed an integral part of the lives of the people. Without any gender discrimination boys and girls in their childhood would be sent to the Kalaris for practicing. With social life undergoing changes, the position of Kalaris and their influence changed. Today, Kalaripayattu is staged during festivals and other occasions as a showpiece. People are more interested in kalari treatment (as a system of medicine) and Marmachikitsa (treatment of vital parts).",
    },
        {
            id: 10,
            name:"Bharatanatyam",
            image:"bh.jpg",
            description:"Bharatanatyam is one of the most popular and widely practiced classical dance styles of India, with sculptural evidence dating back nearly 3000 years. A highly spiritual and dedicatory dance form, Bharatanatyam's roots go back to the Hindu temples of Tamil Nadu, in South India",
            desc2:"Bharatanatyam, a pre-eminent Indian classical dance form presumably the oldest classical dance heritage of India is regarded as mother of many other Indian classical dance forms. Conventionally a solo dance performed only by women, it initiated in the Hindu temples of Tamil Nadu and eventually flourished in South India. Theoretical base of this form traces back to 'Natya Shastra', the ancient Sanskrit Hindu text on the performing arts. A form of illustrative anecdote of Hindu religious themes and spiritual ideas emoted by dancer with excellent footwork and impressive gestures its performance repertoire includes nrita, nritya and natya.  Accompanists include a singer, music and particularly the guru who directs and conducts the performance. It also continues to inspire several art forms including paintings and sculptures starting from the spectacular 6th to 9th century CE temple sculpturesOne of the five great epics of Tamil Literature, 'Silappatikaram' (~2nd century CE) has a direct reference to this dance form.The Shiva temple of Kanchipuram that is decorated with carvings dating back to a period between 6th to 9th centuries CE manifests the development of this dance form by around the mid first millennium CE. Many ancient Hindu temples are embellished with sculptures of Lord Shiva in Bharatanatyam dance poses.The eastern gopuram of the 12th century Thillai Natarajar Temple, Chidambaram, of Tamil Nadu dedicated to Lord Shiva bears sculptures depicting 108 poses of Bharatanatyam, referred as karanas in 'Natya Shastra', that are intricately carved in small rectangular panels. Another notable sculpture can be seen in the Cave 1 of Karnataka's Badami cave temples dating back to the 7th century where a 5 feet tall sculpture of Lord Shiva is depicted as Nataraja doing Tandava dance.  The 18 arms of the Shiva sculpture expresses mudras or hand gestures that are part of Bharatanatyam.",
            
            },




    

]                                                                                                                                                                                                                                       